<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Exploratory Data Analysis (EDA) Report of Import Export Dataest</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="01_import_export_eda_files/libs/clipboard/clipboard.min.js"></script>
<script src="01_import_export_eda_files/libs/quarto-html/quarto.js"></script>
<script src="01_import_export_eda_files/libs/quarto-html/popper.min.js"></script>
<script src="01_import_export_eda_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="01_import_export_eda_files/libs/quarto-html/anchor.min.js"></script>
<link href="01_import_export_eda_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="01_import_export_eda_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="01_import_export_eda_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="01_import_export_eda_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="01_import_export_eda_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><strong>Exploratory Data Analysis (EDA) Report of Import Export Dataest</strong></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Author: Asad Raza Virk</p>
<p>Email: asad.raza.virk@gmail.com</p>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">1. <strong>Introduction</strong></h2>
<ul>
<li><p><strong>Dataset Name</strong>: Imports_Exports V23</p></li>
<li><p><strong>Source</strong>: https://www.kaggle.com/datasets/willianoliveiragibin/imports-exports-v23/data</p></li>
<li><p><strong>Date of Analysis</strong>: 2024/10/24</p></li>
<li><p><strong>Objective</strong> : The objective of this exploratory data analysis (EDA) is to gain insights into the import-export dataset by examining patterns, trends, and key factors that influence international trade. Specifically, this report aims to:</p>
<ul>
<li><p><strong>Understand the structure of the dataset</strong>: Analyze the overall composition of the dataset, including the number of records, types of variables, and data completeness.</p></li>
<li><p><strong>Identify key trade indicators</strong>: Investigate key metrics such as trade volumes, value of imports and exports, major trade routes, and trading partners over time.</p></li>
<li><p><strong>Analyze product categories</strong>: Examine the distribution of different product categories in terms of their import and export values to identify the most significant commodities.</p></li>
<li><p><strong>Explore geographical trends</strong>: Analyze the countries or regions involved in the import-export activities to identify the top importing and exporting countries and any regional patterns.</p></li>
<li><p><strong>Detect seasonality or time-based trends</strong>: Identify any trends or seasonal variations in trade activities over time (e.g., monthly, quarterly, or yearly trends).</p></li>
<li><p><strong>Evaluate data quality</strong>: Detect and handle any missing values, outliers, or inconsistencies in the dataset to ensure reliable results.</p></li>
<li><p><strong>Uncover potential correlations</strong>: Investigate relationships between different variables (e.g., country, product type, trade value) to uncover significant patterns that may impact trade dynamics.</p></li>
</ul></li>
</ul>
</section>
<section id="importing-the-python-libraries" class="level2">
<h2 class="anchored" data-anchor-id="importing-the-python-libraries">2. <strong>Importing the Python Libraries</strong></h2>
<pre><code>    Follwoing python libraries are used for the analysis:
    
- `pandas` : For data manipulation and analysis.
- `numpy` : For numerical operations.
- `matplotlib.pyplot` : For data visualization.
- `seaborn` : For data visualization.</code></pre>
<div id="cell-4" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import the libraries</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="environment-setup" class="level3">
<h3 class="anchored" data-anchor-id="environment-setup">Environment Setup</h3>
<div id="cell-6" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set the environment to print all the columns</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>pd.set_option(<span class="st">'display.max_columns'</span>, <span class="va">None</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="importing-the-data" class="level3">
<h3 class="anchored" data-anchor-id="importing-the-data">Importing the data</h3>
<p>The dataset is imported from the csv file named as data.csv which is stored in the data folder of the directory as this notebook.</p>
<div id="cell-8" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import the dataset from the data folder of the is project folder , file name is 'data.csv'</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>dataset <span class="op">=</span> pd.read_csv(<span class="st">'data/data.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="composition-of-dataset" class="level2">
<h2 class="anchored" data-anchor-id="composition-of-dataset">4. <strong>Composition of Dataset</strong></h2>
<section id="data-structure-and-data-types" class="level3">
<h3 class="anchored" data-anchor-id="data-structure-and-data-types">4.1. <strong>Data Structure and Data Types</strong></h3>
<p>The Structure is examined and the Data types of the columns are checked.</p>
</section>
<section id="dataset-dimensions" class="level3">
<h3 class="anchored" data-anchor-id="dataset-dimensions">4.1.1 <strong>Dataset Dimensions</strong></h3>
<div id="cell-12" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the dimensions of the dataset using the shape attribute</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The dataset has </span><span class="sc">{}</span><span class="st"> rows and </span><span class="sc">{}</span><span class="st"> columns"</span>.<span class="bu">format</span>(dataset.shape[<span class="dv">0</span>],dataset.shape[<span class="dv">1</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The dataset has 15000 rows and 12 columns</code></pre>
</div>
</div>
</section>
<section id="inspection-of-data-set" class="level3">
<h3 class="anchored" data-anchor-id="inspection-of-data-set">4.1.2. <strong>Inspection of Data Set</strong></h3>
<div id="cell-14" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">## Inspect the dataset</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># the first 5 rows of the dataset using the head method</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(dataset.head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                         Transaction_ID           Country    Product  \
0  e3e70682-c209-4cac-a29f-6fbed82c07cd          Colombia   describe   
1  f728b4fa-4248-4e3a-8a5d-2f346baa9455             Chile  president   
2  f7c1bd87-4da5-4709-9471-3d60c8a70639  Christmas Island     agency   
3  e443df78-9558-467f-9ba9-1faf7a024204           Finland     policy   
4  23a7711a-8133-4876-b7eb-dcd9e87a1613       New Zealand   positive   

  Import_Export Shipping_Method          Port     Category  Quantity    Value  \
0        Export             Air    Robertbury    Machinery      1979  9506.57   
1        Export             Air      Shahport     Clothing      5763  7100.91   
2        Export             Air      Adamfort    Furniture      2592  7226.42   
3        Export             Air     Juliebury  Electronics      2622  2817.29   
4        Export             Sea  East Randall    Machinery      6975   657.80   

         Date  Customs_Code   Weight  
0  07-12-2023        620537  4248.65  
1  04-04-2023        927600  4340.81  
2  09-05-2022        996084  4886.14  
3  03-04-2023        555981  4406.74  
4  23-07-2021        741778  1497.16  </code></pre>
</div>
</div>
</section>
<section id="data-types" class="level3">
<h3 class="anchored" data-anchor-id="data-types">4.1.3 <strong>Data Types</strong></h3>
<pre><code>In this section, we will examine the data types of each column in the dataset to ensure that they are correctly interpreted by pandas.</code></pre>
<div id="cell-16" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># print the datatypes of the columns using the dtypes attribute in tabular form</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Data types of the columns"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(dataset.dtypes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Data types of the columns
Transaction_ID      object
Country             object
Product             object
Import_Export       object
Shipping_Method     object
Port                object
Category            object
Quantity             int64
Value              float64
Date                object
Customs_Code         int64
Weight             float64
dtype: object</code></pre>
</div>
</div>
</section>
<section id="the-metadata-and-column-information" class="level3">
<h3 class="anchored" data-anchor-id="the-metadata-and-column-information">4.2.4. <strong>The Metadata and Column Information</strong></h3>
<p>The data types are the kinds of values stored in each column of the import-export dataset. Here’s an interpretation of each data type:</p>
<ul>
<li><p><strong>Transaction_ID (object)</strong>: The column contains alphanumeric values, A unique identifier for each trade transaction, ensuring every entry can be tracked and referenced individually.</p></li>
<li><p><strong>Country (object)</strong>: The country of origin (for imports) or destination (for exports), represented as strings</p></li>
<li><p><strong>Product (object)</strong>: The specific product involved in the trade, which are also strings.</p></li>
<li><p><strong>Import_Export (object)</strong>: A clear indicator of whether the transaction is an import or export, stored as a string.</p></li>
<li><p><strong>Shipping_Method (object)</strong>: The mode of transportation (e.g., Air, Sea, Land) used to move the goods, stored as strings.</p></li>
<li><p><strong>Port (object)</strong>: The entry or departure port where the transaction was processed, stored as strings.</p></li>
<li><p><strong>Category (object)</strong>: The product category (e.g., Electronics, Clothing, Machinery), stored as strings.</p></li>
<li><p><strong>Quantity (int64)</strong>: The amount of the product traded, stored as integers (64-bit precision).</p></li>
<li><p><strong>Value (float64)</strong>: The monetary value of the trade, in U.S. dollars, stored as floating-point numbers (decimal values).</p></li>
<li><p><strong>Date (object)</strong>: The date when the transaction occurred. Dates are represented as strings in this column, and may need conversion to a proper datetime format for further analysis.</p></li>
<li><p><strong>Customs_Code (int64)</strong>: The Harmonized System (HS) or customs code for the product, stored as 64-bit integers.</p></li>
<li><p><strong>Weight (float64)</strong>: The product’s weight in kilograms, stored as floating-point numbers (decimal values).</p></li>
</ul>
</section>
<section id="handling-of-incorrect-data-types" class="level3">
<h3 class="anchored" data-anchor-id="handling-of-incorrect-data-types">4.2.5. <strong>Handling of Incorrect Data Types</strong></h3>
<pre><code>The Dates column is converted to datetime format for further analysis.</code></pre>
<div id="cell-19" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># convert the datatype of the 'Date' column to datetime using the to_datetime method</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>dataset[<span class="st">'Date'</span>] <span class="op">=</span> pd.to_datetime(dataset[<span class="st">'Date'</span>], dayfirst<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="high-cardinality-columns" class="level3">
<h3 class="anchored" data-anchor-id="high-cardinality-columns">4.2.6. <strong>High Cardinality Columns</strong></h3>
<pre><code>The high cardinality columns are identified and examined to determine if they need further processing.</code></pre>
<div id="cell-21" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># identify the high cardinality columns in the dataset using the nunique method</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"High cardinality columns"</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(dataset.nunique())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>High cardinality columns
Transaction_ID     15000
Country              243
Product              971
Import_Export          2
Shipping_Method        3
Port               10657
Category               5
Quantity            7755
Value              14884
Date                1827
Customs_Code       14881
Weight             14775
dtype: int64</code></pre>
</div>
</div>
<p>The following columns with their corresponding unique value counts:</p>
<ul>
<li><p><strong>Transaction_ID ( 15,000 unique values)</strong>: This column has high cardinality, as it contains a unique ID for almost every transaction, which is typical in datasets where each row represents an individual transaction. This column might not be useful for modeling because it doesn’t provide any meaningful pattern, just a unique identifier.</p></li>
<li><p><strong>Country (243 unique values)</strong>: With 243 unique values, the cardinality of this column is moderately high. This could be significant when analyzing data based on country-level trade patterns, but for certain machine learning models, this could require special handling (e.g., one-hot encoding or feature embedding).</p></li>
<li><p><strong>Product (971 unique values)</strong>: The Product column has relatively high cardinality, with 971 distinct products. This indicates a large variety of items being traded, which could impact modeling, especially if you want to analyze trends by product category.</p></li>
<li><p><strong>Import_Export (2 unique values)</strong>: This column has very low cardinality, as it only contains two distinct values, likely representing whether a transaction is an “Import” or “Export.” It’s simple and can be easily encoded.</p></li>
<li><p><strong>Shipping_Method (3 unique values)</strong>: Similarly, this column has low cardinality, likely indicating three different shipping methods. This won’t cause any significant issue during modeling.</p></li>
<li><p><strong>Port (10,657 unique values)</strong>: The Port column has extremely high cardinality, with 10,657 unique entries. This represents a large number of different ports used in the transactions, which might complicate analysis. Handling high cardinality features like this might involve grouping ports by region or other characteristics to reduce complexity.</p></li>
<li><p><strong>Category (5 unique values)</strong>: The Category column has very low cardinality, which means only a few distinct categories are represented. This column is straightforward to encode.</p></li>
<li><p><strong>Quantity (7,755 unique values)</strong>: The Quantity column shows moderately high cardinality, with 7,755 unique values. This variation in quantities traded suggests a diverse range of product sizes/quantities being shipped, and this feature is likely numeric, so handling this in a model would be relatively easy.</p></li>
<li><p><strong>Value (14,884 unique values)</strong>: The Value column has very high cardinality, indicating a wide range of monetary transaction values. Since this is a continuous numeric feature, it may not require special handling beyond normalization or scaling.</p></li>
<li><p><strong>Date (1,827 unique values)</strong>: The Date column has moderately high cardinality, reflecting the number of distinct dates on which transactions occurred. Dates may need to be converted into a more useful format (e.g., extracting features like year, month, or day of the week).</p></li>
<li><p><strong>Customs_Code (14,881 unique values)</strong>: The Customs_Code column also has very high cardinality, with each transaction likely having a different customs classification. It may need special handling like grouping codes into broader categories.</p></li>
<li><p><strong>Weight (14,775 unique values)</strong>: This column, which likely represents the weight of the traded goods, has high cardinality. Like the Value column, it is a numeric feature, so standard scaling or transformation techniques would be sufficient.</p></li>
</ul>
</section>
<section id="unit-consistency-check" class="level3">
<h3 class="anchored" data-anchor-id="unit-consistency-check">4.2.7. <strong>Unit Consistency Check</strong></h3>
<pre><code>The consistency of units in the dataset is checked to ensure that all values are in the same unit of measurement. The `Product` , `port` and `Date` columns had some inconsistencies , which will be handled at the appropriate time. While numerical columns like `Quantity`, `Value`, and `Weight` are expected to be in the same unit of measurement (e.g., kilograms, U.S. dollars), it is important to verify this assumption to avoid errors in analysis.</code></pre>
</section>
</section>
<section id="missing-values" class="level2">
<h2 class="anchored" data-anchor-id="missing-values">4.3. <strong>Missing Values</strong></h2>
<pre><code>The missing values in the dataset are checked.</code></pre>
<div id="cell-25" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the missing values in the dataset using the isnull method and also print the percentage of missing values </span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co"># by rounding the number to 2 decimal places</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>missing_values <span class="op">=</span> dataset.isnull().<span class="bu">sum</span>()</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>missing_values_percentage <span class="op">=</span> <span class="bu">round</span>((missing_values<span class="op">/</span><span class="bu">len</span>(dataset))<span class="op">*</span><span class="dv">100</span>,<span class="dv">2</span>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Missing values in the dataset"</span>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pd.concat([missing_values,missing_values_percentage],axis<span class="op">=</span><span class="dv">1</span>,keys<span class="op">=</span>[<span class="st">'Missing values'</span>,<span class="st">'Percentage'</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Missing values in the dataset
                 Missing values  Percentage
Transaction_ID                0         0.0
Country                       0         0.0
Product                       0         0.0
Import_Export                 0         0.0
Shipping_Method               0         0.0
Port                          0         0.0
Category                      0         0.0
Quantity                      0         0.0
Value                         0         0.0
Date                          0         0.0
Customs_Code                  0         0.0
Weight                        0         0.0</code></pre>
</div>
</div>
<p>As per the above table, there are no missing values in the dataset.</p>
</section>
<section id="duplicates" class="level2">
<h2 class="anchored" data-anchor-id="duplicates">4.4. <strong>Duplicates</strong></h2>
<pre><code>The duplicate rows in the dataset are checked.</code></pre>
<div id="cell-28" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check ducplicates in the dataset using the duplicated method</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>duplicates <span class="op">=</span> dataset.duplicated().<span class="bu">sum</span>()</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Number of duplicates in the dataset: "</span>,duplicates)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of duplicates in the dataset:  0</code></pre>
</div>
</div>
<hr>
</section>
<section id="distribution-of-data" class="level2">
<h2 class="anchored" data-anchor-id="distribution-of-data">5 <strong>Distribution of Data</strong></h2>
<p>In this section , the distribution of the data is examined. The distribution of the data is important to understand the spread of the data and to identify any outliers or anomalies.</p>
<section id="summary-statistics" class="level3">
<h3 class="anchored" data-anchor-id="summary-statistics">5.1. <strong>Summary Statistics</strong></h3>
<pre><code>The descriptive statistics of the numerical columns are examined to understand the distribution of the data.</code></pre>
</section>
<section id="measures-of-central-tendency" class="level3">
<h3 class="anchored" data-anchor-id="measures-of-central-tendency">5.1.1 <strong>Measures of Central Tendency</strong></h3>
<pre><code>The measures of central tendency (mean, median, and mode) are calculated for the numerical columns to understand the central values around which the data is distributed.</code></pre>
<div id="cell-33" class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># print the summary statistics of the dataset using the describe method in tabular form</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Summary statistics of the dataset"</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(dataset.describe())</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Summary statistics of the dataset
           Quantity         Value                        Date  Customs_Code  \
count  15000.000000  15000.000000                       15000   15000.00000   
mean    4980.554733   5032.931120  2022-03-02 20:42:48.960000  549507.95920   
min        1.000000    102.120000         2019-09-07 00:00:00  100041.00000   
25%     2517.000000   2552.750000         2020-12-06 00:00:00  325635.50000   
50%     4958.500000   5045.705000         2022-03-02 00:00:00  545432.00000   
75%     7458.250000   7504.700000         2023-05-27 00:00:00  777988.00000   
max    10000.000000   9999.130000         2024-09-06 00:00:00  999964.00000   
std     2866.166690   2857.593897                         NaN  260886.91886   

             Weight  
count  15000.000000  
mean    2492.118859  
min        0.570000  
25%     1243.482500  
50%     2476.135000  
75%     3747.392500  
max     4999.930000  
std     1451.378507  </code></pre>
</div>
</div>
<p><strong>Interpretation of Summary Statistics</strong>: The summary statistics give a detailed overview of the key numeric columns in the dataset, including Quantity, Value, Customs_Code, and Weight, along with some other columns like Date (treated as an object here). Below is the interpretation for each column based on the summary statistics provided:</p>
<p><strong>Quantity</strong>:</p>
<ul>
<li><strong>Count</strong>: 15,000 entries (all rows have data for this field).</li>
<li><strong>Mean</strong>: The average quantity is around 4,980 units.</li>
<li><strong>Min</strong>: The minimum quantity is 1, indicating that some transactions involved just a single unit.</li>
<li><strong>25% Quartile</strong>: The bottom 25% of the transactions involve quantities up to 2,517 units.</li>
<li><strong>50% (Median)</strong>: Half of the transactions involve quantities of up to 4,958 units.</li>
<li><strong>75% Quartile</strong>: The top 25% of the transactions have quantities up to 7,458 units.</li>
<li><strong>Max</strong>: The largest quantity in a transaction is 10,000 units.</li>
<li><strong>Std Dev (Standard Deviation)</strong>: A standard deviation of 2,866 indicates moderate variability in the quantities of items traded.</li>
</ul>
<p><strong>Value</strong>:</p>
<ul>
<li><strong>Count</strong>: 15,000 entries (all rows have data for this field).</li>
<li><strong>Mean</strong>: The average transaction value is approximately $5,023.</li>
<li><strong>Min</strong>: he smallest transaction value is $102.12, indicating a very small trade.</li>
<li><strong>25% Quartile</strong>: The bottom 25% of transactions are valued up to $2,552.</li>
<li><strong>50% (Median)</strong>: The middle transaction value is $5,045.</li>
<li><strong>75% Quartile</strong>: The top 25% of transactions are valued up to %7,504.</li>
<li><strong>Max</strong>: The highest transaction value is $9,999.</li>
<li><strong>Std Dev (Standard Deviation)</strong>: The standard deviation of $2,857 shows significant variability in transaction values, suggesting a wide range of transaction sizes.</li>
</ul>
<p><strong>Customs_Code</strong>:</p>
<ul>
<li><strong>Count</strong>: 15,000 customs codes, meaning no missing data.</li>
<li><strong>Mean</strong>: The average customs code is approximately 549,507.95, but since this is likely a categorical or encoded numeric feature, its interpretation as a “mean” might not be meaningful.</li>
<li><strong>Min</strong>: The smallest customs code is 100,041.</li>
<li><strong>25% Quartile</strong>: The bottom 25% of customs codes are up to 325,635.</li>
<li><strong>50% (Median)</strong>: Half of the transactions have customs codes up to 545,432.</li>
<li><strong>75% Quartile</strong>: The top 25% of customs codes go up to 777,988.</li>
<li><strong>Max</strong>: The highest customs code is 999,964.</li>
<li><strong>Std Dev</strong>: The standard deviation of 260,886 indicates that the customs codes are widely spread, reinforcing the idea that this might represent distinct categories or groups.</li>
</ul>
<p><strong>Weight</strong>:</p>
<ul>
<li><strong>Count</strong>: 15,000 entries (complete data).</li>
<li><strong>Mean</strong>: The average weight of the transactions is approximately 2,492.12 kg.</li>
<li><strong>Min</strong>: The smallest weight recorded is 0.57 kg, indicating small parcels or shipments.</li>
<li><strong>25% Quartile</strong>: 25% of the transactions weigh up to 1,243.48 kg.</li>
<li><strong>50% (Median)</strong>: Half of the transactions weigh up to 2,476.13 kg.</li>
<li><strong>75% Quartile</strong>: The top 25% of the transactions weigh up to 3,747.39 kg.</li>
<li><strong>Max</strong>: The largest transaction involves 4,999.93 kg of weight.</li>
<li><strong>Std Dev</strong>: The standard deviation of 1,451.37 kg shows that there is moderate variation in the weights of the transactions.</li>
</ul>
<p><strong>Date</strong></p>
<ul>
<li><strong>Min</strong>: The earliest transaction date is September 7, 2019.</li>
<li><strong>25% Quartile</strong>: By December 6, 2020, 25% of the transactions had already occurred.</li>
<li><strong>50% (Median)</strong>: By March 2, 2022, half of the transactions had occurred.</li>
<li><strong>75% Quartile</strong>: By May 27, 2023, 75% of the transactions had occurred.</li>
<li><strong>Max</strong>: The most recent transaction in the dataset occurred on September 6, 2024.</li>
<li><strong>NaN Std Dev</strong>: The standard deviation for the date is not provided, as it is not a numeric column.</li>
</ul>
</section>
<section id="measures-of-dispersion" class="level3">
<h3 class="anchored" data-anchor-id="measures-of-dispersion">5.1.2 <strong>Measures of Dispersion</strong></h3>
<pre><code>The measures of dispersion (range, variance, standard deviation) are calculated for the numerical columns to understand the spread of the data.</code></pre>
<div id="cell-36" class="cell" data-execution_count="38">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Measure the Variance, Standard Deviation, IQR and Range  of the numerical columns in the dataset i.e. 'Quantity', 'Value' and 'Weight' columns</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Variance</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>variance <span class="op">=</span> dataset[[<span class="st">'Quantity'</span>,<span class="st">'Value'</span>,<span class="st">'Weight'</span>]].var()</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Variance of the columns"</span>)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(variance)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span> (<span class="st">"------------------------------------"</span>)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Standard Deviation</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>std_dev <span class="op">=</span> dataset[[<span class="st">'Quantity'</span>,<span class="st">'Value'</span>,<span class="st">'Weight'</span>]].std()</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Standard Deviation of the columns"</span>)</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(std_dev)</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span> (<span class="st">"------------------------------------"</span>)</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a><span class="co"># IQR</span></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>IQR <span class="op">=</span> dataset[[<span class="st">'Quantity'</span>,<span class="st">'Value'</span>,<span class="st">'Weight'</span>]].quantile(<span class="fl">0.75</span>) <span class="op">-</span> dataset[[<span class="st">'Quantity'</span>,<span class="st">'Value'</span>,<span class="st">'Weight'</span>]].quantile(<span class="fl">0.25</span>)</span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"IQR of the columns"</span>)</span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(IQR)</span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span> (<span class="st">"------------------------------------"</span>)</span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Range</span></span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a>Range <span class="op">=</span> dataset[[<span class="st">'Quantity'</span>,<span class="st">'Value'</span>,<span class="st">'Weight'</span>]].<span class="bu">max</span>() <span class="op">-</span> dataset[[<span class="st">'Quantity'</span>,<span class="st">'Value'</span>,<span class="st">'Weight'</span>]].<span class="bu">min</span>()</span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Range of the columns"</span>)</span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(Range)</span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span> (<span class="st">"------------------------------------"</span>)</span>
<span id="cb29-25"><a href="#cb29-25" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Variance of the columns
Quantity    8.214911e+06
Value       8.165843e+06
Weight      2.106500e+06
dtype: float64
------------------------------------
Standard Deviation of the columns
Quantity    2866.166690
Value       2857.593897
Weight      1451.378507
dtype: float64
------------------------------------
IQR of the columns
Quantity    4941.25
Value       4951.95
Weight      2503.91
dtype: float64
------------------------------------
Range of the columns
Quantity    9999.00
Value       9897.01
Weight      4999.36
dtype: float64
------------------------------------</code></pre>
</div>
</div>
<p><strong>Interpretation of Measures of Dispersion</strong></p>
<p>Measures of dispersion tell us how spread out the data is within a dataset. The reuslts provide variance, standard deviation, interquartile range (IQR), and range for the columns Quantity, Value, and Weight. Let’s interpret each measure:</p>
<ul>
<li><p><strong>Variance</strong> Variance quantifies the spread of the data from the mean. A higher variance indicates that the data points are more dispersed.</p>
<ul>
<li><strong>Quantity (8,214,911)</strong>: The variance of quantity is high, showing that the number of items per transaction varies greatly.</li>
<li><strong>Value (8,165,843)</strong>: The high variance indicates significant fluctuations in the monetary value of transactions.</li>
<li><strong>Weight (2,106,500)</strong>: Though lower than the others, the variance of weight still shows substantial variability in shipment sizes.</li>
</ul></li>
<li><p><strong>Standard Deviation</strong> Standard deviation is the square root of variance and is expressed in the same unit as the data. It’s easier to interpret than variance as it directly reflects the data’s spread.</p>
<ul>
<li><strong>Quantity (2,866.17)</strong>: The standard deviation suggests that the number of items traded typically deviates from the mean by around 2,866 units.</li>
<li><strong>Value (2,857.59)</strong>: The monetary value of transactions tends to deviate from the mean by approximately $2,857.</li>
<li><strong>Weight (1,451.38)</strong>: The weight of shipments deviates from the mean by about 1,451 kg. This indicates variability in shipment sizes, but not as extreme as the variation in quantity or value.</li>
</ul></li>
<li><p><strong>Interquartile Range (IQR)</strong> The IQR measures the spread of the middle 50% of the data, and it’s robust to outliers.</p>
<ul>
<li><strong>Quantity (4,941.25)</strong>: The middle 50% of transactions differ by approximately 4,941 units, which is a large range, again highlighting the diversity in the number of items traded.</li>
<li><strong>Value (4,951.95)</strong>: The monetary value of the middle 50% of transactions differs by about $4,951.</li>
<li><strong>Weight (2,503.91)</strong>: The middle 50% of shipments have a weight difference of around 2,504 kg, indicating moderate dispersion in the weight of traded items.</li>
</ul></li>
<li><p>R<strong>ange</strong> The range is the difference between the maximum and minimum values, which provides the full spread of the data.</p>
<ul>
<li><strong>Quantity (9,999.00)</strong>: The range of 9,999 units shows the difference between the largest and smallest transactions in terms of quantity. This suggests some very large transactions.</li>
<li><strong>Value (9,897.01)</strong>: The range of $9,897 in value suggests there are transactions that are quite small and others that are much larger.</li>
<li><strong>Weight (4,999.36)</strong>: The range of weights (4,999.36 kg) shows a moderate spread in the size of shipments, from very small to quite large shipments.</li>
</ul></li>
</ul>
</section>
<section id="measures-of-shape" class="level3">
<h3 class="anchored" data-anchor-id="measures-of-shape">5.1.3 <strong>Measures of Shape</strong></h3>
<pre><code>The measures of shape (skewness, kurtosis) are calculated for the numerical columns to understand the distribution of the data.</code></pre>
<div id="cell-39" class="cell" data-execution_count="40">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize the measure of shape i.e. skewness and kurtosis of the numerical columns in the dataset i.e. 'Quantity', 'Value' and 'Weight' columns</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Skewness</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>skewness <span class="op">=</span> dataset[[<span class="st">'Quantity'</span>,<span class="st">'Value'</span>,<span class="st">'Weight'</span>]].skew()</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Skewness of the columns"</span>)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(skewness)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span> (<span class="st">"------------------------------------"</span>)</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Kurtosis</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>kurtosis <span class="op">=</span> dataset[[<span class="st">'Quantity'</span>,<span class="st">'Value'</span>,<span class="st">'Weight'</span>]].kurt()</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Kurtosis of the columns"</span>)</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(kurtosis)</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span> (<span class="st">"------------------------------------"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Skewness of the columns
Quantity    0.019183
Value       0.008283
Weight      0.025247
dtype: float64
------------------------------------
Kurtosis of the columns
Quantity   -1.182017
Value      -1.193535
Weight     -1.208368
dtype: float64
------------------------------------</code></pre>
</div>
</div>
<p><strong>Interpretation of Measures of Shape</strong></p>
<pre><code>The measures of shape, skewness and kurtosis, describe the distribution of the data in each column. Skewness indicates whether the data is symmetric or biased in one direction, while kurtosis measures the "tailedness" of the distribution, which helps in identifying outliers.</code></pre>
<ul>
<li><p><strong>Skewness</strong></p>
<ul>
<li><p>Skewness measures the asymmetry of the distribution.</p>
<ul>
<li>A skewness of 0 indicates a perfectly symmetrical distribution.</li>
<li>Positive skewness (&gt;0) indicates a distribution with a longer tail on the right (right-skewed).</li>
<li>Negative skewness (&lt;0) indicates a distribution with a longer tail on the left (left-skewed).</li>
</ul></li>
<li><p>Interpretation:</p>
<ul>
<li><p><strong>Quantity (0.019183)</strong>: The skewness is very close to zero, indicating that the distribution of quantity is nearly symmetrical, meaning the number of items traded doesn’t have significant outliers or extreme skew in either direction.</p></li>
<li><p><strong>Value (0.008283)</strong>: Similarly, the skewness of the value column (in $USD) is close to zero, showing a nearly symmetrical distribution. This suggests that the majority of transactions have values that are evenly spread, without extreme high or low outliers.</p></li>
<li><p><strong>Weight (0.025247)</strong>: The skewness is also close to zero, meaning the distribution of shipment weight (in kg) is nearly symmetric, suggesting that small and large shipments occur with similar frequency and there are no extreme outliers on either end.</p></li>
</ul></li>
</ul></li>
<li><p><strong>Kurtosis</strong></p>
<ul>
<li><p>Kurtosis measures the “tailedness” or the peak of the distribution.</p>
<ul>
<li>A kurtosis of 3 indicates a normal distribution (mesokurtic).</li>
<li>A kurtosis &lt; 3 indicates a flatter distribution with fewer extreme values (platykurtic).</li>
<li>A kurtosis &gt; 3 indicates a distribution with heavier tails and more extreme outliers (leptokurtic).</li>
</ul></li>
<li><p>Interpretation:</p>
<ul>
<li><p><strong>Quantity (-1.182017)</strong>: The negative kurtosis suggests a platykurtic distribution, meaning the distribution of the number of items traded has fewer outliers and is relatively flatter compared to a normal distribution. The transactions are more centered around the mean, with fewer extreme quantities.</p></li>
<li><p><strong>Value (-1.193535)</strong>: The value column (in $USD) also shows a platykurtic distribution. This indicates that most transaction values are clustered around the average value, with fewer extremely high or low-value transactions. The dataset does not have many extreme outliers in terms of transaction value.</p></li>
<li><p><strong>Weight (-1.208368)</strong>: The negative kurtosis in the weight column (in kg) suggests that the distribution of weights is also platykurtic, meaning most shipments have weights close to the average. There are fewer extreme weights, indicating a more consistent range of shipment sizes.</p></li>
</ul></li>
</ul></li>
<li><p><strong>General Insights</strong>:</p>
<ul>
<li><p><strong>Skewness</strong>: All three columns (Quantity, Value, Weight) have very small positive skewness values, meaning that the distributions are nearly symmetrical with minimal skew in any direction. This suggests that the number of items traded, the transaction values, and the shipment weights are fairly balanced in the dataset, with no strong lean toward very high or very low values.</p></li>
<li><p><strong>Kurtosis</strong>: All three columns have negative kurtosis, indicating that the distributions are flatter than a normal distribution (platykurtic). This means that the data is concentrated around the mean, with fewer outliers or extreme values in terms of quantity, value, and weight. The transactions are more consistently distributed, without large deviations from the average.</p></li>
</ul></li>
<li><p><strong>Conclusion</strong>: The overall interpretation of skewness and kurtosis shows that the dataset is well-balanced with respect to the number of items traded, their value in dollars, and their weight in kilograms. The distributions are symmetric and exhibit a low likelihood of outliers, which indicates consistent and typical trading behavior across the dataset.</p></li>
</ul>
</section>
<section id="advance-techniques-for-relationships" class="level3">
<h3 class="anchored" data-anchor-id="advance-techniques-for-relationships">5.1.4 <strong>Advance Techniques for Relationships</strong></h3>
<pre><code>The relationships between the numerical columns are examined using advanced techniques like covariance amd correlation matrices to identify any patterns or associations.</code></pre>
<div id="cell-42" class="cell" data-execution_count="41">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the covariance and correlation of the numerical columns in the dataset i.e. 'Quantity', 'Value' and 'Weight' columns</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Covariance</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>covariance <span class="op">=</span> dataset[[<span class="st">'Quantity'</span>,<span class="st">'Value'</span>,<span class="st">'Weight'</span>]].cov()</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Covariance of the columns"</span>)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(covariance)</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span> (<span class="st">"------------------------------------"</span>)</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation</span></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>correlation <span class="op">=</span> dataset[[<span class="st">'Quantity'</span>,<span class="st">'Value'</span>,<span class="st">'Weight'</span>]].corr()</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Correlation of the columns"</span>)</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(correlation)</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span> (<span class="st">"------------------------------------"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Covariance of the columns
              Quantity         Value        Weight
Quantity  8.214911e+06 -2.355745e+04  2.823106e+04
Value    -2.355745e+04  8.165843e+06  1.877632e+04
Weight    2.823106e+04  1.877632e+04  2.106500e+06
------------------------------------
Correlation of the columns
          Quantity     Value    Weight
Quantity  1.000000 -0.002876  0.006786
Value    -0.002876  1.000000  0.004527
Weight    0.006786  0.004527  1.000000
------------------------------------</code></pre>
</div>
</div>
<p><strong>Interpretation of Advanced Techniques of Relationships: Covariance and Correlation</strong></p>
<p>This analysis focuses on the covariance and correlation between the columns Quantity, Value, and Weight. These measures help in understanding the relationships and dependencies between these numerical variables.</p>
<ul>
<li><p><strong>Covariance</strong> Covariance measures how two variables change together. A positive covariance means the variables tend to increase together, while a negative covariance means that as one variable increases, the other tends to decrease. The magnitude of the covariance is influenced by the scale of the variables.</p>
<ul>
<li><strong>Interpretation</strong>:
<ul>
<li><p><strong>Quantity and Value (-2.355745e+04)</strong>: The negative covariance indicates that there is a slight inverse relationship between the number of items traded and the value of the transaction. This means that as the quantity increases, the value tends to decrease slightly, although the magnitude of the covariance is small.</p></li>
<li><p><strong>Quantity and Weight (2.823106e+04)</strong>: The positive covariance suggests that quantity and weight tend to increase together, meaning that larger quantities of items are usually associated with heavier shipments. The magnitude is moderate, indicating a reasonable relationship between these two variables.</p></li>
<li><p><strong>Value and Weight (1.877632e+04)</strong>: The positive covariance indicates that value and weight increase together, although the relationship is relatively weak. This suggests that more expensive transactions tend to involve heavier shipments, but the relationship is not strong.</p></li>
</ul></li>
<li><strong>Key Insight on Covariance</strong>: The covariance values suggest that quantity and value move in opposite directions, while weight tends to move in the same direction as both quantity and value, although the relationships are weak or moderate.</li>
</ul></li>
<li><p><strong>Correlation</strong> Correlation measures the strength and direction of a linear relationship between two variables. It is a standardized measure, ranging from -1 to 1:</p>
<ul>
<li><p>1 indicates a perfect positive correlation.</p></li>
<li><p>-1 indicates a perfect negative correlation.</p></li>
<li><p>0 indicates no linear correlation.</p></li>
<li><p><strong>Interpretation</strong>:</p>
<ul>
<li><p><strong>Quantity and Value (-0.002876)</strong>: The correlation between quantity and value is close to zero, meaning there is almost <strong>no linear relationship</strong> between the number of items traded and the value of the transaction. This suggests that large quantities do not necessarily correspond to higher or lower transaction values.</p></li>
<li><p><strong>Quantity and Weight (0.006786)</strong>: The small positive correlation indicates that there is <strong>a very weak positive relationship</strong> between quantity and weight. While larger shipments tend to be heavier, the relationship is almost negligible.</p></li>
<li><p><strong>Value and Weight (0.004527)</strong>: Similarly, the correlation between value and weight is close to zero, indicating almost <strong>no linear relationship</strong>. This suggests that the value of a transaction doesn’t strongly depend on the weight of the shipment.</p></li>
</ul></li>
<li><p><strong>Key Insight on Correlation</strong>: The correlation values are close to zero for all pairs of variables, indicating that there is no strong linear relationship between quantity, value, and weight. This implies that these variables are largely independent of each other in terms of their linear relationship.</p></li>
</ul></li>
<li><p><strong>General Insights</strong>:</p>
<ul>
<li><strong>Covariance</strong> provides a more general sense of how variables move together, with small relationships observed between quantity and weight and value and weight.</li>
<li><strong>Correlation</strong> reveals that there is no strong linear dependency between the variables, as all correlation coefficients are close to zero, indicating very weak relationships.</li>
</ul></li>
<li><p><strong>Summary</strong>:</p>
<ul>
<li>The relationships between quantity, value, and weight are weak and almost negligible in terms of their linear correlation.</li>
<li>While covariance shows a slight tendency for quantity and weight to increase together and a slight inverse relationship between quantity and value, these relationships are too weak to make significant conclusions about their dependencies.</li>
</ul></li>
</ul>
</section>
<section id="distribution-of-categorical-data" class="level3">
<h3 class="anchored" data-anchor-id="distribution-of-categorical-data">5.1.5. <strong>Distribution of Categorical Data</strong></h3>
<pre><code>The distribution of the categorical columns is examined to understand the spread of the data and identify any patterns or anomalies.</code></pre>
<div id="cell-45" class="cell" data-execution_count="44">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>dataset.columns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="44">
<pre><code>Index(['Transaction_ID', 'Country', 'Product', 'Import_Export',
       'Shipping_Method', 'Port', 'Category', 'Quantity', 'Value', 'Date',
       'Customs_Code', 'Weight'],
      dtype='object')</code></pre>
</div>
</div>
<div id="cell-46" class="cell" data-execution_count="46">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the distribution of categorical columns in the dataset i.e. 'Country', 'Product' and 'Import_Export', 'Shipping_Method', 'Port' and 'Category' columns</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Country</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Distribution of Country column"</span>)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(dataset[<span class="st">'Country'</span>].value_counts())</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span> (<span class="st">"------------------------------------"</span>)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Product</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Distribution of Product column"</span>)</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(dataset[<span class="st">'Product'</span>].value_counts())</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span> (<span class="st">"------------------------------------"</span>)</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Import_Export</span></span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Distribution of Import_Export column"</span>)</span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(dataset[<span class="st">'Import_Export'</span>].value_counts())</span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span> (<span class="st">"------------------------------------"</span>)</span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Shipping_Method</span></span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Distribution of Shipping_Method column"</span>)</span>
<span id="cb41-19"><a href="#cb41-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(dataset[<span class="st">'Shipping_Method'</span>].value_counts())</span>
<span id="cb41-20"><a href="#cb41-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span> (<span class="st">"------------------------------------"</span>)</span>
<span id="cb41-21"><a href="#cb41-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-22"><a href="#cb41-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Port</span></span>
<span id="cb41-23"><a href="#cb41-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Distribution of Port column"</span>)</span>
<span id="cb41-24"><a href="#cb41-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(dataset[<span class="st">'Port'</span>].value_counts())</span>
<span id="cb41-25"><a href="#cb41-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span> (<span class="st">"------------------------------------"</span>)</span>
<span id="cb41-26"><a href="#cb41-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-27"><a href="#cb41-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Category</span></span>
<span id="cb41-28"><a href="#cb41-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Distribution of Category column"</span>)</span>
<span id="cb41-29"><a href="#cb41-29" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(dataset[<span class="st">'Category'</span>].value_counts())</span>
<span id="cb41-30"><a href="#cb41-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span> (<span class="st">"------------------------------------"</span>)</span>
<span id="cb41-31"><a href="#cb41-31" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Distribution of Country column
Country
Congo               133
Korea               113
Pakistan             79
Pitcairn Islands     79
Israel               79
                   ... 
Myanmar              45
Reunion              44
Liechtenstein        44
Faroe Islands        43
Palau                41
Name: count, Length: 243, dtype: int64
------------------------------------
Distribution of Product column
Product
family     28
bank       27
music      27
address    27
card       27
           ..
science     7
state       7
energy      7
deep        6
rich        6
Name: count, Length: 971, dtype: int64
------------------------------------
Distribution of Import_Export column
Import_Export
Import    7569
Export    7431
Name: count, dtype: int64
------------------------------------
Distribution of Shipping_Method column
Shipping_Method
Sea     5054
Air     4995
Land    4951
Name: count, dtype: int64
------------------------------------
Distribution of Port column
Port
West Michael         20
Lake Michael         20
Port David           17
New Michael          14
East Michael         14
                     ..
Port Amandaton        1
Hillborough           1
Port Victoriatown     1
Camerontown           1
Shahport              1
Name: count, Length: 10657, dtype: int64
------------------------------------
Distribution of Category column
Category
Clothing       3048
Furniture      3024
Electronics    3021
Machinery      3010
Toys           2897
Name: count, dtype: int64
------------------------------------</code></pre>
</div>
</div>
<p><strong>Interpretation of the Distribution of Categorical Columns</strong>:</p>
<p>The results provide the distribution of several categorical columns: Country, Product, Import_Export, Shipping_Method, and Port. Here’s the interpretation for each:</p>
<ul>
<li><strong>Country</strong>
<ul>
<li>There are 243 unique countries in the dataset.</li>
<li>The highest number of transactions come from Congo (133), followed by Korea (113).</li>
<li>Other countries like Pakistan, Pitcairn Islands, and Israel have around 79 transactions each.</li>
<li>Smaller countries like Palau have much fewer transactions, around 41.</li>
<li>The spread across countries suggests some concentration in a few countries (like Congo and Korea), while many other countries have a smaller presence in the dataset.</li>
<li><strong>Insight:</strong> The dataset seems to have more transactions concentrated in a few key countries, with the rest having much smaller involvement in trade.</li>
</ul></li>
<li><strong>Product</strong>
<ul>
<li>There are 971 unique products in the dataset.</li>
<li>The most frequent products are family (28 transactions), followed by bank, music, address, and card (27 transactions each).</li>
<li>Other products like science, state, and energy have fewer occurrences (7 transactions).</li>
<li>The least frequent products include deep and rich (6 transactions).</li>
<li><strong>Insight</strong>: The product distribution is wide, but most products appear only a few times, with a handful of products occurring more frequently. This suggests a diverse product portfolio, with a few products playing a central role in transactions.</li>
</ul></li>
<li><strong>Import_Export</strong>
<ul>
<li>Import transactions (7,569) slightly outnumber Export transactions (7,431).</li>
<li><strong>Insight:</strong> The import and export activities are almost evenly balanced, suggesting the dataset represents both sides of international trade with nearly equal emphasis.</li>
</ul></li>
<li><strong>Shipping_Method Column</strong>
<ul>
<li>There are three shipping methods: Sea (5,054 transactions), Air (4,995 transactions), and Land (4,951 transactions).</li>
<li>The distribution is relatively even across all shipping methods.</li>
<li><strong>Insight</strong>: The use of different shipping methods is balanced, indicating that sea, air, and land transport all play a significant role in trade operations.</li>
</ul></li>
<li><strong>Port</strong>
<ul>
<li>There are 10,657 unique ports in the dataset, indicating a large geographical spread.</li>
<li>The most frequent ports include West Michael and Lake Michael (20 transactions each), followed by Port David (17), New Michael (14), and East Michael (14).</li>
<li>Many ports have only 1 transaction each, such as Port Amandaton, Hillborough, and Shahport.</li>
<li><strong>Insight</strong>: The port distribution shows that while a few ports handle a significant number of transactions, the majority of the ports are used very infrequently, which reflects the diversity in the shipping routes used in trade.</li>
<li>Port names like Michael, David, and Amandaton suggest a mix of real and fictional port names, which may require further investigation for accuracy.</li>
<li><strong>The problem of port names are like spelling mistakes and the same port name with different spellings is also observed</strong>.</li>
</ul></li>
<li><strong>General Insights</strong>:
<ul>
<li>The Country and Product distributions indicate that a few key entities dominate trade, with many smaller contributors.</li>
<li>The balance between Import and Export, as well as the use of Shipping Methods, suggests an evenly distributed logistics operation.</li>
<li>The Port distribution suggests global shipping routes, but with a strong reliance on a few key ports.</li>
</ul></li>
</ul>
<p>This diversity in categorical data reflects the complexity and wide geographical range of the dataset’s trade operations.</p>
</section>
</section>
<section id="visualisation" class="level2">
<h2 class="anchored" data-anchor-id="visualisation">5.2. <strong>Visualisation</strong></h2>
<pre><code>The data is visualized using various plots to identify patterns, trends, and relationships in the dataset.</code></pre>
<section id="histogram" class="level3">
<h3 class="anchored" data-anchor-id="histogram">5.2.1. <strong>Histogram</strong></h3>
<pre><code>The histograms of the numerical columns are plotted to visualize the distribution of the data.</code></pre>
<div id="cell-49" class="cell" data-execution_count="51">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the histogram of the numerical columns in the dataset i.e. 'Quantity', 'Value' and 'Weight' columns also label the x and y axis</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Quantity</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>,<span class="dv">5</span>))</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>sns.histplot(dataset[<span class="st">'Quantity'</span>], kde<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Quantity'</span>)</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frequency'</span>)</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Histogram of Quantity'</span>)</span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_import_export_eda_files/figure-html/cell-18-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>The distribution of <strong>Quantity</strong> is mostly uniform, with some fluctuations across different quantity ranges.</li>
<li>The KDE curve shows a slight rise around 1,000 and 7,000 units, indicating a small preference for these quantity levels in the dataset.</li>
<li>There is a minor dip at the start of the range (close to 0) and at the higher end (close to 10,000).</li>
<li>The overall shape suggests that transactions involve a wide range of item quantities with no strong concentration in any specific range, but there are slightly more transactions in the middle ranges (1,000 - 7,000 units).</li>
</ul>
<div id="cell-51" class="cell" data-execution_count="50">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Value</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>,<span class="dv">5</span>))</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>sns.histplot(dataset[<span class="st">'Value'</span>], kde<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Value'</span>)</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frequency'</span>)</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Histogram of Value'</span>)</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_import_export_eda_files/figure-html/cell-19-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>The <strong>Value</strong> (in USD) is also relatively uniformly distributed, similar to the quantity.</li>
<li>The KDE curve shows that there is a higher frequency of transactions with values between 1,000 and 7,000 USD.</li>
<li>There are slight dips near 0 and 10,000 USD, meaning that fewer transactions involve extreme low or high values.</li>
<li>The uniformity, with some concentration in the middle, suggests that the dataset has a balanced spread of transaction values, without strong bias toward very expensive or very inexpensive transactions.</li>
</ul>
<div id="cell-53" class="cell" data-execution_count="49">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Weight</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>,<span class="dv">5</span>))</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>sns.histplot(dataset[<span class="st">'Weight'</span>], kde<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Weight'</span>)</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frequency'</span>)</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Histogram of Weight'</span>)</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_import_export_eda_files/figure-html/cell-20-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>The <strong>Weight</strong> (in kg) distribution shows similar patterns to the other variables, with a near-uniform spread across the range from 0 to 5,000 kg.</li>
<li>The KDE curve shows slight peaks around the 1,000 - 2,000 kg and 4,000 - 5,000 kg ranges, meaning that some shipments tend to cluster in these weight ranges.</li>
<li>Like the other variables, the frequency drops at the extremes (close to 0 kg and near 5,000 kg), with most transactions falling somewhere in the middle.</li>
<li>This distribution indicates a broad range of shipment sizes, with a slight preference for medium to larger shipments.</li>
</ul>
<p><strong>General Insights:</strong> - All three histograms show relatively uniform distributions with some minor fluctuations, indicating that the dataset has a wide range of values for quantity, value, and weight. - The slight concentration in the middle ranges (1,000 - 7,000 for Quantity and Value, and 1,000 - 5,000 for Weight) suggests that most transactions are of medium size in terms of quantity, value, and shipment weight, with fewer extreme small or large transactions. - The KDE curves further reinforce the idea that the distributions are relatively balanced, with no extreme skewness or concentration in any one area.</p>
<p>These visualizations suggest that the dataset is well-rounded and diverse in terms of the size, value, and weight of transactions.</p>
</section>
<section id="density-plots" class="level3">
<h3 class="anchored" data-anchor-id="density-plots">5.3. <strong>Density Plots</strong></h3>
<pre><code>The density plots of the numerical columns are plotted to estimate the probability density function of variance in the data.</code></pre>
<div id="cell-57" class="cell" data-execution_count="58">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the Density plot of the numerical columns in the dataset i.e. 'Quantity', 'Value' and 'Weight'  to estimate the probability </span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="co"># density function of the variable</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Quantity</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>,<span class="dv">5</span>))</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>sns.kdeplot(dataset[<span class="st">'Quantity'</span>], fill<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Quantity'</span>)</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Density'</span>)</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Density plot of Quantity'</span>)</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_import_export_eda_files/figure-html/cell-21-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>The plot shows a flat density across the range from 0 to 10,000 units. This suggests a uniform distribution, where all quantity levels have almost equal likelihood of occurring.</li>
<li>There are small fluctuations around 2,000 and 6,000 units, indicating that transactions involving these quantities might occur slightly more frequently, but overall, the density is evenly spread.</li>
<li>The variance in the quantity data is consistent across the range, with no significant peaks or drops, indicating that different quantities are equally probable.</li>
</ul>
<div id="cell-59" class="cell" data-execution_count="57">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Value</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>,<span class="dv">5</span>))</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>sns.kdeplot(dataset[<span class="st">'Value'</span>], fill<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Value'</span>)</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Density'</span>)</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Density plot of Value'</span>)</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_import_export_eda_files/figure-html/cell-22-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>The Value (in USD) also shows a relatively flat density, indicating that transactions across the full range of values (from 0 to 10,000 USD) have almost equal likelihood.</li>
<li>Small fluctuations around 2,000 and 9,000 USD suggest that there may be slightly more transactions involving values in these ranges, but overall, the distribution remains uniform.</li>
<li>The density plot shows a uniform spread of transaction values, meaning the dataset contains a wide range of transaction amounts without significant variance in specific value ranges.</li>
</ul>
<div id="cell-61" class="cell" data-execution_count="56">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Weight</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>,<span class="dv">5</span>))</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>sns.kdeplot(dataset[<span class="st">'Weight'</span>], fill<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Weight'</span>)</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Density'</span>)</span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Density plot of Weight'</span>)</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01_import_export_eda_files/figure-html/cell-23-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>The Weight (in kg) distribution follows a similar pattern, with a flat density across the range from 0 to 5,000 kg.</li>
<li>Slight fluctuations can be seen around 1,000 and 4,000 kg, suggesting these weight ranges might occur slightly more often, but overall, the distribution remains even.</li>
<li>The uniform shape of the density plot indicates that the variance in weights is consistent across different shipment sizes, with no strong bias toward small or large weights.</li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>